### ISSUE TITLE
OAuthAccessTokenException: The access_token provided is invalid.

### ISSUE THREAD

**Issue by srsandy** [totemstech/instagram-node#122]
I Just registered a new client and I m getting 

```
var ig = require('instagram-node').instagram();
ig.use({ access_token: 'xxxxxxxxxxxxxxxxxxxxxxxxx' });
ig.use({
	client_id: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
	client_secret: 'xxxxxxxxxxxxxxxxxxxx'
});

ig.media_popular(function(err, media, limit){
	if(err) { throw err; }
	console.log(media);
}); 
```

`/Users/sandeep/Desktop/git/express-app-build/app.js:21
	if(err) { throw err; }
	          ^

Error: OAuthAccessTokenException: The access_token provided is invalid.
    at handle_error (/Users/sandeep/Desktop/git/express-app-build/node_modules/instagram-node/lib/instagram.js:242:19)
    at /Users/sandeep/Desktop/git/express-app-build/node_modules/instagram-node/lib/instagram.js:908:16
    at IncomingMessage.<anonymous> (/Users/sandeep/Desktop/git/express-app-build/node_modules/instagram-node/lib/instagram.js:197:18)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by srsandy** [comment]
Can you pls help me with this pls.. 
how to solve this problem.

**Comment by srsandy** [comment]
can someone pls answer me

**Comment by jefe-spain** [comment]
the last commit of this repo is 3 years ago @srsandy , I don't think It works anymore 👍

**Comment by srsandy** [comment]
@jefe-spain But then how i hit the API using this ?

**Comment by Jarmahent** [comment]
Use the Instagram api tutorial to create your own access_token with: `https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=code`

I couldnt get it to work myself using client_id and client_secret so just remove those and leave:

`ig.use({ access_token: 'xxxxxxxxxxxxxxxxxxxxxxxxx' });`

That should work.


Edit: Oops I just noticed how old this repo and issues are...
