### ISSUE TITLE
Error: Please supply client_id and client_secret via use()

### ISSUE THREAD

**Issue by grantmac** [totemstech/instagram-node#23]
On the first hit of the route /authorize_user authorises oaky. 
On further hits of the route /authorize_user it results in a "Error: Please supply client_id and client_secret via use()" error, even thought both the  client_id and client_secret's are set in the use.

**Comment by codeOfRobin** [comment]
Got this issue again. 

Error: Please supply client_id and client_secret via use()

**Comment by andrewfschorr** [comment]
This seems to be happening again for me as well, subsequent hits after the initial one throw the above error.

**Comment by dhirajsharma072** [comment]
I am getting same error "Please supply client_id and client_secret via use()" in version 0.5.8.
Please suggest solution for this. Thanks!

**Comment by dhirajsharma072** [comment]
Hi,
I found the solution of error "Please supply client_id and client_secret via use()" in version 0.5.8.
 Here is my sample code for solution. 

```
var instagram = require('instagram-node').instagram();
var redirect_url = config.instagram.callbackURL; // callback url of instagram

exports.getRedirectionURL = function () {
  instagram.use({
    client_id: config.instagram.clientID,               //app client id
    client_secret: config.instagram.clientSecret  // app secret 
  });
  return instagram.get_authorization_url(redirect_url, {
    scope: ['basic']
  });
};
```

Each time before calling instagram.get_authorization_url(), please call instagram.use(option).

Hope it will help for you.

**Comment by born2net** [comment]
I see the same issue recently...
regards

Sean

**Comment by pxlprfct** [comment]
I'm still seeing this issue - first auth is fine, but subsequent auths will fail.
I slightly modified @dhirajsharma072 fix - and all seems good.
