### ISSUE TITLE
Get all comments

### ISSUE THREAD

**Issue by renancouto** [totemstech/instagram-node#35]
I know that this is not a limitation of this lib, but I think you guys might have a clue or two on how to get all comments from a media because Instagram's API only return the last 150.
Any help is appreciate, thanks!

**Comment by juicytone** [comment]
@spolu dear sir,

**Comment by juicytone** [comment]
@spolu hello, could you please help me to solve the same issue? I can't retrieve (with API), load and even view more comments than 150. There was a way to grab all comment via PC before (iconosquare service). I tried even to grab all comments one-by-one on my cellphone, but the application started to hide all comments. 

I would kindly appreciate your help!
