### ISSUE TITLE
Search by Facebook ID

### ISSUE THREAD

**Issue by texaspacm** [totemstech/instagram-node#47]
I do not have a FourSquare ID, but I do have a Facebook ID.   I'm assuming I use the "ig.location_search" function, but not sure how to pass in the Facebook ID, or if it's even possible. 

Any idea?

Thank you!

**Comment by n1t0** [comment]
Hi @texaspacm, you can indeed search for instagram locations using Facebook ID: 
```javascript
ig.location_search({ facebook_places_id: 'FACEBOOK_ID' }, function(err, results) {
  console.log(err, result);
});
```

This will give you an instagram location id, from which you'll be able to retrieve medias using:
```javascript
ig.location('LOCATION_ID', function(err, results) {});
```
