### ISSUE TITLE
How to user user subscription?

### ISSUE THREAD

**Issue by datpham23** [totemstech/instagram-node#49]
I'm just curious how you actually use this api since I don't see how you specify the userid.

ig.add_user_subscription('http://MYHOST/user', [options,] function(err, result, remaining, limit){});

Ive tried doing something like this but that didn't work either.
```
   var callBackURL = 'http://'+server.ip+'/user/userid';
			ig.add_user_subscription(callBackURL, [], function(err, result, remaining, limit){
				
			});

	express.post("/user/:userid", function(req,res){
		console.log("user call back");
	});
```

**Comment by n1t0** [comment]
Hi @datpham23, while using this, you actually subscribe to all your client's authenticated users. So you don't specify any user_id.
You can find more information here: https://instagram.com/developer/realtime/#user-subscriptions

**Comment by adammoisa** [comment]
Hi, I am getting an error that: OAuthClientException: Missing client_secret URL parameter when trying to use this call. Here is my call:

```
ig.add_user_subscription('http://localhost:3000/user', function(err, result, remaining, limit){
      if (err) {
        console.log('Error: ', err);
      } else {
        console.log('Success ', result);
      }
});
```
