### ISSUE TITLE
add_tag_subscription returning OAuthParameterException error

### ISSUE THREAD

**Issue by renettarenula** [totemstech/instagram-node#50]
I am trying to use the add_tag_subscription to use the realtime Instagram API. However, I can't seem to use this endpoint.

When I run: 

instagram.add_tag_subscription('funny', 'localtunnelurl/callback', { verify_token: 'funnytag' }, function(err, result, remaining, limit) { console.log(err); console.log(result) });

it returns:

{ [Error: OAuthParameterException: Missing client_id or access_token URL parameter.]
  code: 400,
  error_type: 'OAuthParameterException',
  error_message: 'Missing client_id or access_token URL parameter.',
  retry: [Function] }

I am sure my setup of client_id and client_secret is correct since other endpoints like tag_media_recent is returning results as expected. I know that the subscription endpoint requires client_id and client_secret but I have pass these information in the instagram.use() method. Perhaps it is a bug for this subscription endpoint method? Or is there something on my end that I forgot to do? Documentation doesn't state that I need to do anything else except just provide the callback url.

**Comment by n1t0** [comment]
Hi @renettarenula, I've test it on my side, and it seems to be working fine.

Here is the snippet that I used:
```javascript
var ig = require('instagram-node').instagram({});

ig.use({
  client_id: 'YOUR_CLIENT_ID',
  client_secret: 'YOUR_CLIENT_SECRET'
});

ig.add_tag_subscription('paris', 'http://requestb.in/wek9rdwe', function(err, result) {
  console.log(err, result);
});
```
Result:
```
null { object: 'tag',
  object_id: 'paris',
  aspect: 'media',
  callback_url: 'http://requestb.in/wek9rdwe',
  type: 'subscription',
  id: '17649189' }
```

Can you post the code you have been using ? (without your client_id/secret)

**Comment by laurent-h** [comment]
Same issue for me although it was working a few weeks ago...

@n1t0: It seems to work when positioning Content-Type: application/x-www-form-urlencoded and correct Content-Length in call(...) with method='POST'.

**Comment by michellechandra** [comment]
I am also getting this error, although it's worked in the past just fine.

**Comment by n1t0** [comment]
This is weird, I didn't manage to reproduce it on my end. Does it work better with `0.5.7`?

**Comment by michellechandra** [comment]
@n1t0 updating the version fixed it, thanks!

**Comment by n1t0** [comment]
Awesome! Thanks to @laurent-h who fixed it!

@renettarenula Could you also test it with the new version?

**Comment by renettarenula** [comment]
@n1t0 Thanks for the reply! It seems to be working fine for me as well!
