### ISSUE TITLE
OAuthRateLimitException with pagination

### ISSUE THREAD

**Issue by lemoslincoln** [totemstech/instagram-node#53]
I want take just the fotos from a tag of today
I create this filter on ig.tag_media_recent or with the pagination?

var hdl = function(err, medias, pagination, limit) {
    if(err){
      console.log(err);
    } else {
      if(pagination.next) {
      console.log('Variavel pagination: %j', pagination);
      pagination.next(hdl); }  
    }  
  };
ig.tag_media_recent(hashtag, hdl);

**Comment by gido** [comment]
Hi,

The thing is that by default [`tag_media_recent`](https://instagram.com/developer/endpoints/tags/#get_tags_media_recent) will return **all medias** with your specified hashtag if you follow the pagination with the next method (like you did) without an _exit clause_. Without an exit/filter clause you quickly reach the [Instagram API limit](https://instagram.com/developer/limits/).

Here is some solutions:

#### 1. (recommended) Use one of the filter parameters allowed for this endpoint (`count`, `min_tag_id` or `max_tag_id`):

```javascript
// will only return the 200 more recent medias for hashtag
ig.tag_media_recent(hashtag, { count: 200 }, hdl);
```

#### 2. define an exit clause based on your logic

```javascript
var someTimestamp = ...;
var hdl = function(err, medias, pagination, limit) {
  // ...
  if (medias[medias.length - 1].created_time < someTimestamp) {
    return ;
  }
  // ...
}
```
