### ISSUE TITLE
you must provide a client_id

### ISSUE THREAD

**Issue by bicccio** [totemstech/instagram-node#55]
In the last days i get this error after the instagram authentication form:
code: 400,                                                                                                                             
error_type: 'OAuthException',                                                                          
error_message: 'You must provide a client_id',

The code i'm trying is the one present in the 'Server-Side Authentication using OAuth and the Instagram API' section of your github page... I'm sure the client_id is set.

thx.
Fabrizio

**Comment by etrom** [comment]
I am also having this problem.

**Comment by etrom** [comment]
@bicccio I fixed it by updating to the latest version 0.5.7

**Comment by bicccio** [comment]
Thx @etrom... it works!!!

**Comment by rasoolbi** [comment]
Excuse me iam also having same problem but didn't understand your solution , can u give some more details about that..Thanks in advance

**Comment by bicccio** [comment]
@rasoolbi u have to update to the latest version.

**Comment by rasoolbi** [comment]
instagram version or api version..can you plz tell me...i was blocked here.

**Comment by bicccio** [comment]
instagram-node version...

**Comment by rasoolbi** [comment]
https://api.instagram.com/oauth/access_token API URL
client_id,client_secret,grant_type,redirect_uri,code these are the post parameters iam sending.
Response am getting:
Array
(
    [code] => 400
    [error_type] => OAuthException
    [error_message] => You must provide a client_id
)
i didn't get instagram-node? and how to do that?
