### ISSUE TITLE
Uncaught SyntaxError: Unexpected token o

### ISSUE THREAD

**Issue by EliuFlorez** [totemstech/instagram-node#56]
Error en Followers
var user_id = 'XXXXXXXXXXXXXX';
api.user_followers(user_id, {count:100}, function(err, users, pagination, remaining, limit) {
			if (!err) {

			} else {
				console.log(err);
			}
		});

![error-followers](https://cloud.githubusercontent.com/assets/784787/7987093/242e0b34-0aa5-11e5-817c-0f4eec269f02.jpg)

**Comment by EliuFlorez** [comment]
success

**Comment by tom2strobl** [comment]
What did you change @EliuFlorez ?
