### ISSUE TITLE
api.user_follows returns empty array

### ISSUE THREAD

**Issue by venil7** [totemstech/instagram-node#90]
`api.user_follows` and `api.user_followers` returns empty array `[]` for a sanboxed user who definately has plenty follows and followers

**Comment by robbiegleeson** [comment]
Looks like it's an Instagram issue. If you call this `https://api.instagram.com/v1/users/self/follows?access_token=ACCESS_TOKEN` you'll get the same response

**Comment by robbiegleeson** [comment]
Same here but it looks to be an Instagram issue as opposed to a package issue.

**Comment by venil7** [comment]
yes, I can confirm that,
Instagram gives you no data on users sitting outside your sandbox

closing, as irrelevant for this repo..

**Comment by robbiegleeson** [comment]
FYI I just discovered that you need to add Sandbox users to your client. You can add up to a maximum of 10. If they like your data or are one of your followers then `api.user_followers` and `api.media_likes` will return values.
